sensor:
  - platform: scd4x
    address: ${sdc41_addr}
    co2:
      name: "CO2"
      id: sens_co2
    temperature:
      name: "Temperature SCD41"
      id: sens_temp_scd
    humidity:
      name: "Humidity SCD41"
      id: sens_hum_scd
    update_interval: 30s
    automatic_self_calibration: false
