# ============================================================================
#
# M2 MODULE BASIC DESIGN FOR BASIC FUNCTIONS
#
# Adapt the configurations, names and other to your needs
#
# ============================================================================
mqtt:
  on_message:
    - topic: ${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 1/command
      then:
        - if:
            condition:
              lambda: 'return x == "ON";'
            then:
              - switch.turn_on: m2${m2_number_1}_O_channel_1
            else:
              - switch.turn_off: m2${m2_number_1}_O_channel_1
    - topic: ${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 2/command
      then:
        - if:
            condition:
              lambda: 'return x == "ON";'
            then:
              - switch.turn_on: m2${m2_number_1}_O_channel_2
            else:
              - switch.turn_off: m2${m2_number_1}_O_channel_2
    - topic: ${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 3/command
      then:
        - if:
            condition:
              lambda: 'return x == "ON";'
            then:
              - switch.turn_on: m2${m2_number_1}_O_channel_3
            else:
              - switch.turn_off: m2${m2_number_1}_O_channel_3
    - topic: ${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 4/command
      then:
        - if:
            condition:
              lambda: 'return x == "ON";'
            then:
              - switch.turn_on: m2${m2_number_1}_O_channel_4
            else:
              - switch.turn_off: m2${m2_number_1}_O_channel_4
    - topic: ${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 5/command
      then:
        - if:
            condition:
              lambda: 'return x == "ON";'
            then:
              - switch.turn_on: m2${m2_number_1}_O_channel_5
            else:
              - switch.turn_off: m2${m2_number_1}_O_channel_5
    - topic: ${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 6/command
      then:
        - if:
            condition:
              lambda: 'return x == "ON";'
            then:
              - switch.turn_on: m2${m2_number_1}_O_channel_6
            else:
              - switch.turn_off: m2${m2_number_1}_O_channel_6
    - topic: ${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 7/command
      then:
        - if:
            condition:
              lambda: 'return x == "ON";'
            then:
              - switch.turn_on: m2${m2_number_1}_O_channel_7
            else:
              - switch.turn_off: m2${m2_number_1}_O_channel_7
    - topic: ${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 8/command
      then:
        - if:
            condition:
              lambda: 'return x == "ON";'
            then:
              - switch.turn_on: m2${m2_number_1}_O_channel_8
            else:
              - switch.turn_off: m2${m2_number_1}_O_channel_8

# Configuration for PCA chip
pca9554:
  - id: domix_m2${m2_number_1}_busi2c
    address: ${m2_i2c_1}
    i2c_id: ${m2_i2c_id}              # Bus for comunication with DOMIX M1 module
    pin_count: 16
    
# INPUT: from GPIO0_0 up to GPIO0_7 (Port 0) of PCA chip
binary_sensor:
  - platform: gpio
    name: "${m2_name}${m2_number_1} ${m2_input_name} channel 1"
    id: m2${m2_number_1}_I_channel_1
    icon: "mdi:input"
    pin:
      pca9554: domix_m2${m2_number_1}_busi2c
      number: 0
      mode: INPUT
      inverted: false
    on_press:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_input_name} 1/state"
          payload: "ON"
          retain: True
    on_release:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_input_name} 1/state"
          payload: "OFF"
          retain: True       
    web_server:
      sorting_group_id: domix_m2_web
      sorting_weight: 1

  - platform: gpio
    name: "${m2_name}${m2_number_1} ${m2_input_name} channel 2"
    id: m2${m2_number_1}_I_channel_2
    icon: "mdi:input"
    pin:
      pca9554: domix_m2${m2_number_1}_busi2c
      number: 1
      mode: INPUT
    on_press:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_input_name} 2/state"
          payload: "ON"
          retain: True
    on_release:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_input_name} 2/state"
          payload: "OFF"
          retain: True       
    web_server:
      sorting_group_id: domix_m2_web
      sorting_weight: 2

  - platform: gpio
    name: "${m2_name}${m2_number_1} ${m2_input_name} channel 3"
    id: m2${m2_number_1}_I_channel_3
    icon: "mdi:input"
    pin:
      pca9554: domix_m2${m2_number_1}_busi2c
      number: 2
      mode: INPUT
    on_press:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_input_name} 3/state"
          payload: "ON"
          retain: True
    on_release:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_input_name} 3/state"
          payload: "OFF"
          retain: True       
    web_server:
      sorting_group_id: domix_m2_web
      sorting_weight: 3

  - platform: gpio
    name: "${m2_name}${m2_number_1} ${m2_input_name} channel 4"
    id: m2${m2_number_1}_I_channel_4
    icon: "mdi:input"
    pin:
      pca9554: domix_m2${m2_number_1}_busi2c
      number: 3
      mode: INPUT
    on_press:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_input_name} 4/state"
          payload: "ON"
          retain: True
    on_release:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_input_name} 4/state"
          payload: "OFF"
          retain: True       
    web_server:
      sorting_group_id: domix_m2_web
      sorting_weight: 4

  - platform: gpio
    name: "${m2_name}${m2_number_1} ${m2_input_name} channel 5"
    id: m2${m2_number_1}_I_channel_5
    icon: "mdi:input"
    pin:
      pca9554: domix_m2${m2_number_1}_busi2c
      number: 4
      mode: INPUT
    on_press:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_input_name} 5/state"
          payload: "ON"
          retain: True
    on_release:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_input_name} 5/state"
          payload: "OFF"
          retain: True       
    web_server:
      sorting_group_id: domix_m2_web
      sorting_weight: 5

  - platform: gpio
    name: "${m2_name}${m2_number_1} ${m2_input_name} channel 6"
    id: m2${m2_number_1}_I_channel_6
    icon: "mdi:input"
    pin:
      pca9554: domix_m2${m2_number_1}_busi2c
      number: 5
      mode: INPUT
    on_press:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_input_name} 6/state"
          payload: "ON"
          retain: True
    on_release:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_input_name} 6/state"
          payload: "OFF"
          retain: True       
    web_server:
      sorting_group_id: domix_m2_web
      sorting_weight: 6

  - platform: gpio
    name: "${m2_name}${m2_number_1} ${m2_input_name} channel 7"
    id: m2${m2_number_1}_I_channel_7
    icon: "mdi:input"
    pin:
      pca9554: domix_m2${m2_number_1}_busi2c
      number: 6
      mode: INPUT
    on_press:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_input_name} 7/state"
          payload: "ON"
          retain: True
    on_release:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_input_name} 7/state"
          payload: "OFF"
          retain: True       
    web_server:
      sorting_group_id: domix_m2_web
      sorting_weight: 7

  - platform: gpio
    name: "${m2_name}${m2_number_1} ${m2_input_name} channel 8"
    id: m2${m2_number_1}_I_channel_8
    icon: "mdi:input"
    pin:
      pca9554: domix_m2${m2_number_1}_busi2c
      number: 7
      mode: INPUT
    on_press:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_input_name} 8/state"
          payload: "ON"
          retain: True
    on_release:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_input_name} 8/state"
          payload: "OFF"
          retain: True       
    web_server:
      sorting_group_id: domix_m2_web  
      sorting_weight: 8

# Output: from GPIO1_0 up to GPIO1_7 (Port 1) of PCA chip 
switch:
  - platform: gpio
    name: "${m2_name}${m2_number_1} ${m2_output_name} channel 1"
    id: m2${m2_number_1}_O_channel_1
    icon: "mdi:output"
    pin:
      pca9554: domix_m2${m2_number_1}_busi2c
      number: 8
      mode: OUTPUT
      inverted: false
    on_turn_on:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 1/state"
          payload: "ON"
          retain: True
    on_turn_off:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 1/state"
          payload: "OFF"
          retain: True       
    web_server:
      sorting_group_id: domix_m2_web
      sorting_weight: 9

  - platform: gpio
    name: "${m2_name}${m2_number_1} ${m2_output_name} channel 2"
    id: m2${m2_number_1}_O_channel_2
    icon: "mdi:output"
    pin:
      pca9554: domix_m2${m2_number_1}_busi2c
      number: 9
      mode: OUTPUT
    on_turn_on:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 2/state"
          payload: "ON"
          retain: True
    on_turn_off:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 2/state"
          payload: "OFF"
          retain: True       
    web_server:
      sorting_group_id: domix_m2_web
      sorting_weight: 10

  - platform: gpio
    name: "${m2_name}${m2_number_1} ${m2_output_name} channel 3"
    id: m2${m2_number_1}_O_channel_3
    icon: "mdi:output"
    pin:
      pca9554: domix_m2${m2_number_1}_busi2c
      number: 10
      mode: OUTPUT
    on_turn_on:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 3/state"
          payload: "ON"
          retain: True
    on_turn_off:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 3/state"
          payload: "OFF"
          retain: True       
    web_server:
      sorting_group_id: domix_m2_web
      sorting_weight: 11

  - platform: gpio
    name: "${m2_name}${m2_number_1} ${m2_output_name} channel 4"
    id: m2${m2_number_1}_O_channel_4
    icon: "mdi:output"
    pin:
      pca9554: domix_m2${m2_number_1}_busi2c
      number: 11
      mode: OUTPUT
    on_turn_on:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 4/state"
          payload: "ON"
          retain: True
    on_turn_off:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 4/state"
          payload: "OFF"
          retain: True       
    web_server:
      sorting_group_id: domix_m2_web
      sorting_weight: 12

  - platform: gpio
    name: "${m2_name}${m2_number_1} ${m2_output_name} channel 5"
    id: m2${m2_number_1}_O_channel_5
    icon: "mdi:output"
    pin:
      pca9554: domix_m2${m2_number_1}_busi2c
      number: 12
      mode: OUTPUT
    on_turn_on:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 5/state"
          payload: "ON"
          retain: True
    on_turn_off:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 5/state"
          payload: "OFF"
          retain: True       
    web_server:
      sorting_group_id: domix_m2_web
      sorting_weight: 13

  - platform: gpio
    name: "${m2_name}${m2_number_1} ${m2_output_name} channel 6"
    id: m2${m2_number_1}_O_channel_6
    icon: "mdi:output"
    pin:
      pca9554: domix_m2${m2_number_1}_busi2c
      number: 13
      mode: OUTPUT
    on_turn_on:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 6/state"
          payload: "ON"
          retain: True
    on_turn_off:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 6/state"
          payload: "OFF"
          retain: True       
    web_server:
      sorting_group_id: domix_m2_web
      sorting_weight: 14

  - platform: gpio
    name: "${m2_name}${m2_number_1} ${m2_output_name} channel 7"
    id: m2${m2_number_1}_O_channel_7
    icon: "mdi:output"
    pin:
      pca9554: domix_m2${m2_number_1}_busi2c
      number: 14
      mode: OUTPUT
    on_turn_on:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 7/state"
          payload: "ON"
          retain: True
    on_turn_off:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 7/state"
          payload: "OFF"
          retain: True       
    web_server:
      sorting_group_id: domix_m2_web
      sorting_weight: 15

  - platform: gpio
    name: "${m2_name}${m2_number_1} ${m2_output_name} channel 8"
    id: m2${m2_number_1}_O_channel_8
    icon: "mdi:output"
    pin:
      pca9554: domix_m2${m2_number_1}_busi2c
      number: 15
      mode: OUTPUT
    on_turn_on:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 8/state"
          payload: "ON"
          retain: True
    on_turn_off:
      - mqtt.publish:
          topic: "${mqtt_name}/${m2_name}${m2_number_1}/${m2_output_name} 8/state"
          payload: "OFF"
          retain: True       
    web_server:
      sorting_group_id: domix_m2_web
      sorting_weight: 16