substitutions: 
# ----------------------------------------------------------------------------
# DEFAULT SUBSTITUTIONS
# Users can override any of these in their main config file
# ----------------------------------------------------------------------------
  # === Board Name ===
  device_name: my-home-domix            
  friendly_name: "My Home DOMIX"
  mqtt_name: "DOMIX"

# ----------------------------------------------------------------------------
# OTA (Over-The-Air) UPDATE PASSWORD
# ----------------------------------------------------------------------------
  ota_password: ""                        # Username to be defined if needed for ota

# ----------------------------------------------------------------------------
# IP BASIC DATA
# ----------------------------------------------------------------------------
  ethernet_IP: "192.168.1.3"              # Modify according your net
  ethernet_gateway: "192.168.1.1"
  ethernet_subnet: "255.255.255.0"

# ----------------------------------------------------------------------------
# WEB SERVER AUTHENTICATION
# ----------------------------------------------------------------------------
  web_username: "admin"                   # Username to be defined if needed for web access
  web_password: "admin"                   # Username to be defined if needed for web access 

# ----------------------------------------------------------------------------
# MQTT CREDENTIALS
# ----------------------------------------------------------------------------
  mqtt_broker: "192.168.1.42"             # Your MQTT IP address
  mqtt_port: "1883"                       # Standard MQTT port (use 8883 for TLS)
  mqtt_username: ""                       # Leave just "" if not used
  mqtt_password: ""                       # Leave just "" if not used

# ----------------------------------------------------------------------------
# Time Zones
# ----------------------------------------------------------------------------
  timezone: "Europe/Rome"

# ----------------------------------------------------------------------------
# M1 module
# ----------------------------------------------------------------------------
  m1_name: M1               # REMEMBER TO SET THE ADDRESS, UNIQUE FOR ALL PROJECT
  # -------- PLEAESE CHOOSE THE I2C BUS FOR M1 MODULE, ACCORDING TO YOUR CONFIGURATION --------
  m1_i2c_id: bus_screen         # I2C bus for upper board buttons with i2c.yaml file
  # m1_i2c_id: bus_module_7     # I2C bus for upper board buttons with i2c_switch.yaml file
  # ---------------------------------------------------------------------------------------------
  m1_screen_address: 0x3C            # ADDRESS AVAILABLE: 0x3C
  m1_screen_button_address: 0x48     # ADDRESS AVAILABLE: 0x48 -> 0x4A

# ----------------------------------------------------------------------------
# M2 module
# ----------------------------------------------------------------------------
  m2_name: M2               # REMEMBER TO SET THE ADDRESS, UNIQUE FOR ALL PROJECT
  # -------- PLEAESE CHOOSE THE I2C BUS FOR M2 MODULE, ACCORDING TO YOUR CONFIGURATION --------  
  m2_i2c_id: bus_module     # I2C bus to which the module is connected, defined in i2c.yaml
  # m2_i2c_id: bus_module_1     # I2C bus for upper board buttons with i2c_switch.yaml file
  # ---------------------------------------------------------------------------------------------  
  m2_i2c_1: 0x20            # ADDRESS AVAILABLE: 0x20 -> 0x27 
  m2_number_1: _1        
  m2_output_name: Output       # Name of each output channel on MQTT and web page
  m2_input_name: Input         # Name of each input channel on MQTT and web page

# ----------------------------------------------------------------------------
# M3 module
# ----------------------------------------------------------------------------
  m3_name: M3               # REMEMBER TO SET THE ADDRESS, UNIQUE FOR ALL PROJECT
  # -------- PLEAESE CHOOSE THE I2C BUS FOR M3 MODULE, ACCORDING TO YOUR CONFIGURATION --------  
  m3_i2c_id: bus_module     # I2C bus to which the module is connected, defined in i2c.yaml
  # m3_i2c_id: bus_module_1     # I2C bus for upper board buttons with i2c_switch.yaml file
  # ---------------------------------------------------------------------------------------------  
  m3_i2c_1: 0x38            # ADDRESS AVAILABLE: 0x38 -> 0x3F           
  m3_ads_1: 0x4A            # ADDRESS AVAILABLE: 0x48 -> 0x4A  
  m3_number_1: _1           
  m3_channel_name: Channel     # Name of each output channel on MQTT and web page
  
# ----------------------------------------------------------------------------
# M4 module
# ----------------------------------------------------------------------------
  m4_name: M4               # REMEMBER TO SET THE ADDRESS, UNIQUE FOR ALL PROJECT
  # -------- PLEAESE CHOOSE THE I2C BUS FOR M4 MODULE, ACCORDING TO YOUR CONFIGURATION --------  
  m4_i2c_id: bus_module     # I2C bus to which the module is connected, defined in i2c.yaml
  # m4_i2c_id: bus_module_1     # I2C bus for upper board buttons with i2c_switch.yaml file
  # ---------------------------------------------------------------------------------------------  
  m4_i2c_1: 0x39            # ADDRESS AVAILABLE: 0x38 -> 0x3F 
  m4_number_1: _1           
  m4_output_name: Output    # Name of each output channel on MQTT and web page

# ----------------------------------------------------------------------------
# M5 module
# ----------------------------------------------------------------------------
  m5_name: M5               # REMEMBER TO SET THE ADDRESS, UNIQUE FOR ALL PROJECT
  # -------- PLEAESE CHOOSE THE I2C BUS FOR M5 MODULE, ACCORDING TO YOUR CONFIGURATION --------  
  m5_i2c_id: bus_module     # I2C bus to which the module is connected, defined in i2c.yaml
  # m5_i2c_id: bus_module_1     # I2C bus for upper board buttons with i2c_switch.yaml file
  # ---------------------------------------------------------------------------------------------  
  m5_i2c_1: 0x21            # ADDRESS AVAILABLE: 0x20 -> 0x27 
  m5_number_1: _1           
  m5_output_name: Output    # Name of each output channel on MQTT and web page

# ----------------------------------------------------------------------------
# M6 module
# ----------------------------------------------------------------------------
  m6_name: M6               # REMEMBER TO SET THE ADDRESS, UNIQUE FOR ALL PROJECT
  # -------- PLEAESE CHOOSE THE I2C BUS FOR M6 MODULE, ACCORDING TO YOUR CONFIGURATION --------  
  m6_i2c_id: bus_module     # I2C bus to which the module is connected, defined in i2c.yaml
  # m6_i2c_id: bus_module_1     # I2C bus for upper board buttons with i2c_switch.yaml file
  # ---------------------------------------------------------------------------------------------  
  m6_i2c_1: 0x3A            # ADDRESS AVAILABLE: 0x38 -> 0x3F
  m6_ads_1: 0x49            # ADDRESS AVAILABLE: 0x48 -> 0x4A    
  m6_number_1: _1       
  m6_voltage_description: Voltage    # Name of each output channel on MQTT and web page    
  m6_channel_description: Channel     # Name of each output channel on MQTT and web page
  
# ----------------------------------------------------------------------------
# M7 module
# ----------------------------------------------------------------------------
  m7_name: M7               # REMEMBER TO SET THE ADDRESS, UNIQUE FOR ALL PROJECT
  # -------- PLEAESE CHOOSE THE I2C BUS FOR M7 MODULE, ACCORDING TO YOUR CONFIGURATION --------  
  m7_i2c_id: bus_module     # I2C bus to which the module is connected, defined in i2c.yaml
  # m7_i2c_id: bus_module_1     # I2C bus for upper board buttons with i2c_switch.yaml file
  # ---------------------------------------------------------------------------------------------  
  m7_i2c_1: 0x22            # ADDRESS AVAILABLE: 0x20 -> 0x27 
  m7_number_1: _1
  m7_output_name: Output    # Name of each output channel on MQTT and web page

# ----------------------------------------------------------------------------
# M8 module
# ----------------------------------------------------------------------------
  m8_name: M8               # REMEMBER TO SET THE ADDRESS, UNIQUE FOR ALL PROJECT
  # -------- PLEAESE CHOOSE THE I2C BUS FOR M8 MODULE, ACCORDING TO YOUR CONFIGURATION --------  
  m8_i2c_id: bus_module     # I2C bus to which the module is connected, defined in i2c.yaml
  # m8_i2c_id: bus_module_1     # I2C bus for upper board buttons with i2c_switch.yaml file
  # ---------------------------------------------------------------------------------------------  
  m8_i2c_1: 0x23            # ADDRESS AVAILABLE: 0x20 -> 0x27 
  m8_number_1: _1    
  m8_input_name: Input      # Name of each output channel on MQTT and web page

# ----------------------------------------------------------------------------
# M9 module
# ----------------------------------------------------------------------------
  m9_name: M9               # REMEMBER TO SET THE ADDRESS, UNIQUE FOR ALL PROJECT
  # -------- PLEAESE CHOOSE THE I2C BUS FOR M9 MODULE, ACCORDING TO YOUR CONFIGURATION --------  
  m9_i2c_id: bus_module     # I2C bus to which the module is connected, defined in i2c.yaml
  # m9_i2c_id: bus_module_1     # I2C bus for upper board buttons with i2c_switch.yaml file
  # ---------------------------------------------------------------------------------------------  
  m9_i2c_1: 0x3B            # ADDRESS AVAILABLE: 0x38 -> 0x3F 
  m9_buttons_i2c_address: 0x3C   # Buttons Upper Board address
  m9_number_1: _1
  m9_description: garden    
  m9_description_upper: Garden    
  m9_valve_description: Valve

# ----------------------------------------------------------------------------
# S module
#
# is defined into main.yaml file
# ----------------------------------------------------------------------------