sensor:
  - platform: uptime
    id: uptime_s
    update_interval: 60s

interval:
  - interval: 30min
    then:
      - mqtt.publish:
          topic: "${device_name}/Diagnostic/IP"
          payload: !lambda 'return id(ip_address).state;'
      - mqtt.publish:
          topic: "${device_name}/Diagnostic/DNS"
          payload: !lambda 'return id(dns_address).state;'
      - mqtt.publish:
          topic: "${device_name}/Diagnostic/MAC"
          payload: !lambda 'return id(mac_address).state;'

text_sensor:
  - platform: version
    name: "${device_name} Version"
    id: version_esphome
    icon: "mdi:file-copy"
    on_value:
      then:
        - mqtt.publish:
            topic: "${device_name}/Diagnostic/Version"
            payload: !lambda 'return x;'
    web_server:
      sorting_group_id: various

  # Expose WiFi information as sensors
  - platform: ethernet_info
    ip_address:
      name: "${device_name} IP"
      id: ip_address
      icon: "mdi:lan"
      web_server:
        sorting_group_id: various
    dns_address:
      name: "${device_name} DNS"
      id: dns_address
      icon: "mdi:dns"
      web_server:
        sorting_group_id: various
    mac_address:
      name: "${device_name} MAC"
      id: mac_address    
      icon: "mdi:computer"
      web_server:
        sorting_group_id: various

  - platform: template
    name: "${device_name} Uptime"
    icon: "mdi:more-time"
    lambda: |-
      uint32_t dur = id(uptime_s).state;
      int dys = 0;
      int hrs = 0;
      int mnts = 0;
      if (dur > 86399) {
        dys = trunc(dur / 86400);
        dur = dur - (dys * 86400);
      }
      if (dur > 3599) {
        hrs = trunc(dur / 3600);
        dur = dur - (hrs * 3600);
      }
      if (dur > 59) {
        mnts = trunc(dur / 60);
        dur = dur - (mnts * 60);
      }
      char buffer[17];
      sprintf(buffer, "%ud %02uh %02um %02us", dys, hrs, mnts, dur);
      return {buffer};
    update_interval: 60s        
    web_server:
      sorting_group_id: various